### ISSUE TITLE
WantAssertionsSigned param not been taken into account

### ISSUE THREAD

**Issue by cbjims** [lastpass/saml-sdk-java#13]
The exception "Assertion must be signed" is fired even when WantAssertionsSigned is set to false on the SP xml config file : 

org.opensaml.xml.validation.ValidationException: Assertion must be signed
      at com.lastpass.saml.SAMLClient.validateResponse(SAMLClient.java:436)

extract of the SP config file : 
`<SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">`

**Comment by bcopeland** [comment]
This seems like a dangerous option to support though.  I'd hate for someone to unknowingly deploy an SP that has no signature checking as a result of such a change.  What's the use case for enabling unsigned assertions -- your IdP only signs the full response?  As far as I know, most IdPs will have the option to sign assertions and it's not too unreasonable to set them up that way.

**Comment by cbjims** [comment]
Thank you for your response.
We wanted to enable unsigned assertions for testing purpose: 

When the assertions is signed our IDP doesn't send the "Destination" attribute

```
<samlp:Response Version="2.0"
               ID="*****************************"
               IssueInstant="*****************************"
               xmlns:samlp="*****************************"
               >

```

And when the assertions is unsigned our IDP send the "Destination" attribute
```
<samlp:Response xmlns:samlp="*****************************"
                ID="*****************************"
                Version="2.0"
                IssueInstant="*****************************"
                Destination="http://....com"
                >
```


So we wanted to test with unsigned to have the destination attribute.

By the way, when the Destination attribute is not present on the Header we have an exception : 

```
com.lastpass.saml.SAMLException: org.opensaml.xml.validation.ValidationException: Response is destined for a different endpoint
        at com.lastpass.saml.SAMLClient.validateResponse(SAMLClient.java:436)
```

but the endpoint is present elsewhere on the SAML response and after some researches on the net (not really sure), it seems that this attribute should no be mandatory in case the message is signed. 

Thank you for your help.

**Comment by bcopeland** [comment]
I see.  If you don't mind me asking, which idp is that?  Is it the case that, when the assertion is signed, that the response is not signed, and vice-versa?  Or are you trying to process a message that has no signatures at all?

I believe it's the other way around: destination is mandatory if the response is signed -- this makes sense in a way because you can't really trust the unsigned parts of a response, so an attacker could just remove or replace the destination of a different response with the one you are expecting.  See 3.4.5.2 at https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf

So, I guess we could allow to have signed assertion without destination and without signed response, or a signed response and validated destination without a signed assertion, so long as one or the other is enabled, and never allow both unsigned response and unsigned assertion.

On the other hand, I like having very strict requirements on the SP side because the SP is where mistakes can really hurt you -- the best situation is one in which IdP is signing both.

**Comment by cbjims** [comment]
Sorry but I don't really know which IDP it is. (customer's IDP)

As you said the IDP can return 

- (1) a signed assertion without destination and without signed response (I think in this case the destination will be in the assertion within a param named "Recipient", because you're right, you can trust only the signed part), 

- or (2) a signed response and validated destination without a signed assertion.

I don't know why but this IDP doesn't sign both assertion AND response.

http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf
Section 5:

```
A digital signature is not always required in SAML. For example, in some circumstances, signatures may
be "inherited," such as when an unsigned assertion gains protection from a signature on the containing
protocol response message.
```

So it's seems that only signed assertion is allowed?


My problem is : 
In case (1) I have " Response is destined for a different endpoint"
In case (2) I have "Assertion must be signed"

I think I cannot use this IDP with your SP

**Comment by bcopeland** [comment]
I will close this for now -- although I merged the original PR, this is a bit dangerous and against saml2int.org v0.2 (9.1).  if you rework the PR to default to always check assertions (i.e. without WantAssertionSigned="true") then I can revisit.
